// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2FuRkQ432qox8jiOxg9SfBFKi9Ve07Eg',
    appId: '1:960194687927:web:4c70d6c5d9d162e2d92e32',
    messagingSenderId: '960194687927',
    projectId: 'sams-b9782',
    authDomain: 'sams-b9782.firebaseapp.com',
    storageBucket: 'sams-b9782.firebasestorage.app',
    measurementId: 'G-ZNV2G6C8X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldRtm8FIV4zjl5f7irYlYoTL6eOgI8e8',
    appId: '1:960194687927:android:0811637db3d0eb51d92e32',
    messagingSenderId: '960194687927',
    projectId: 'sams-b9782',
    storageBucket: 'sams-b9782.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzYu3tnvVbN9LrmLaWbOQrG5Cj324fkJE',
    appId: '1:960194687927:ios:2642a56115ae1eeed92e32',
    messagingSenderId: '960194687927',
    projectId: 'sams-b9782',
    storageBucket: 'sams-b9782.firebasestorage.app',
    iosBundleId: 'com.example.samsApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzYu3tnvVbN9LrmLaWbOQrG5Cj324fkJE',
    appId: '1:960194687927:ios:2642a56115ae1eeed92e32',
    messagingSenderId: '960194687927',
    projectId: 'sams-b9782',
    storageBucket: 'sams-b9782.firebasestorage.app',
    iosBundleId: 'com.example.samsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2FuRkQ432qox8jiOxg9SfBFKi9Ve07Eg',
    appId: '1:960194687927:web:5a41d34349b22e1ad92e32',
    messagingSenderId: '960194687927',
    projectId: 'sams-b9782',
    authDomain: 'sams-b9782.firebaseapp.com',
    storageBucket: 'sams-b9782.firebasestorage.app',
    measurementId: 'G-9RFDNBRTXT',
  );
}
